name: de
description: A Discord bot that allows you to download attachments from a given channel
version: 1.0.0
repository: https://github.com/shalien/de

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  nyxx: ^6.1.0
  nyxx_commands: ^6.0.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
